name: geoflutterfire_example
description: Demonstrates how to use the Geoflutterfire2 plugin.
publish_to: "none"

environment:
  sdk: "^3.10.8"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  geoflutterfire2:
    path: ../

  cloud_firestore: ^6.1.3
  google_maps_flutter: ^2.14.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
